version: 0.2

run-as: root

env:
  parameter-store:
    MongoDb_url: "/divye/mongo"

phases:
  build:
    commands:
      - sed -i "s/localhost/"MongoDb_url"/" app.js
      - echo Building ...

  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - '**/*'
