version: 0.2

run-as: root

env:
  parameter-store:
    MongoDb_url= "/divye/mondodb_url"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Nodejs

  pre_build:
    commands:
      - npm install
      - echo Installing npm dependencies

  build:
    commands:
      - sed -i "s/localhost/"MongoDb_url"/" app.js
      - echo Build started on 'date'
      - echo Building ...

  post_build:
    commands:
      - echo Build complete

  artifacts:
    files:
      - '**/*'

